<a href="https://colab.research.google.com/github/anamikaprem/Learn.py/blob/main/TASK_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array with elements ranging from 0-15. And find the trace of the array.

In [6]:
import numpy as np 
mat = np.random.randint(0,15,(4,4))
print("Array\n",mat)
print("Trace of the Array is: \n",mat.trace())


Array
 [[12  4 14 11]
 [11 10 13 12]
 [ 0  2  5  5]
 [ 3 10  0 13]]
Trace of the Array is: 
 40


2. Create a matrix with elements [6,1,1],[4,-2,5],[2,8,7].Now find the inverse this matrix.

In [5]:
import numpy as np
mat = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print("Matix\n",mat)
print("\nThe Inverse of Matrix is :\n",np.linalg.inv(mat))


Matix
 [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]

The Inverse of Matrix is :
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


3. Create an 3x3 array with elements ranging from 0-8. And find the norm this array.

In [3]:
import numpy as np 
mat = np.random.randint(0,8,(3,3))
print("Array\n",mat)
print("\nThe Norm of the Matrix is\n",np.linalg.norm(mat))


Array
 [[7 0 2]
 [1 5 4]
 [1 2 5]]

The Norm of the Matrix is
 11.180339887498949


4. Create a 4x4 array whose value ranging from 0-15.And find the eigenvalues and eigenvectors of this array.

In [4]:
import numpy as np
mat = np.random.randint(0,15,(4,4))
print("Array\n",mat)
print("\nThe EigenValue and EigenVectors of the Matrix is\n",np.linalg.eig(mat))

Array
 [[ 7  6  1  9]
 [10  0  0 10]
 [13 14  7  0]
 [14  2  5  5]]

The EigenValue and EigenVectors of the Matrix is
 (array([24.4780569+0.j        , -3.3879047+0.j        ,
       -1.0450761+5.09104783j, -1.0450761-5.09104783j]), array([[-0.43320609+0.j        , -0.55533277+0.j        ,
         0.18938019-0.1982957j ,  0.18938019+0.1982957j ],
       [-0.38667207+0.j        ,  0.04726573+0.j        ,
         0.29430077-0.11338884j,  0.29430077+0.11338884j],
       [-0.63194028+0.j        ,  0.6312732 +0.j        ,
        -0.81815922+0.j        , -0.81815922-0.j        ],
       [-0.513292  +0.j        ,  0.53931959+0.j        ,
        -0.16241006+0.35997562j, -0.16241006-0.35997562j]]))
