<a href="https://colab.research.google.com/github/anamikaprem/Learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [3]:
import numpy as np
x=np.random.random((3,3))
print(x)


[[0.31804081 0.63914125 0.91811932]
 [0.02557723 0.7542728  0.65254824]
 [0.3996258  0.50979081 0.292308  ]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [2]:
import numpy as np
x=np.array([(1,2,3,4),(5,6,7,8),(8,7,6,5),(4,3,2,1)])
y=np.array([(1,2,3,4),(5,6,7,8),(8,7,6,5),(4,3,2,1)])
print(x)
print()
print(y)
print()
x1=x.reshape(2,8)
y1=y.reshape(2,8)
print("after reshaping")
print()
print(x1)
print()
print(y1)
np.vstack((x1,y1))
np.hstack((x1,y1))


[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]

[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]

after reshaping

[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]]

[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]]


array([[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8],
       [8, 7, 6, 5, 4, 3, 2, 1, 8, 7, 6, 5, 4, 3, 2, 1]])