<a href="https://colab.research.google.com/github/anamikaprem/Learn.py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [2]:
import numpy as np
matrix1 = np.random.randint(0,10,(3,3))
matrix2 = np.random.randint(0,10,(3,3)) 
print(matrix1)
print(matrix2)
dot = np.dot(matrix1,matrix2)
print(dot)


[[7 5 4]
 [2 8 9]
 [5 4 3]]
[[5 6 5]
 [2 1 3]
 [8 6 2]]
[[77 71 58]
 [98 74 52]
 [57 52 43]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [3]:
import numpy as np
matrix = [[55,25,15],[30,44,2],[11,45,77]]
print(matrix)
det = np.linalg.det(matrix)
print(det)

[[55, 25, 15], [30, 44, 2], [11, 45, 77]]
137180.0000000001
