<a href="https://colab.research.google.com/github/anamikaprem/Learn.py/blob/main/TASK_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array containing the values ranging from 0 - 15 (use arange function). Then ,
  
  a) split it equally along horizontal.

  b) split it as 4 parts vertically.



In [13]:
import numpy as np
array = np.arange(0,16)
newarr=array.reshape(4,4)
print(newarr)
split = np.array_split(newarr,2)
print("\n Equally Splitting Array \n",split)
print("\n Splitting vertically: \n",np.hsplit(newarr,4))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 Equally Splitting Array 
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]

 Splitting vertically: 
 [array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


2. Create a 3x3 matrix using random module and then,

  a) Find the ceil of the matrix.
  
  b) Find the floor of the matrix.

In [11]:
import numpy as np
matrix = np.random.random_sample(size=(3,3))
print(matrix) 
ceil = np.ceil(matrix)
print("\n Ceil of the Matrix: \n",ceil)
floor = np.floor(matrix)
print("\n Floor of the Matrix: \n",floor)


[[0.68081323 0.4427938  0.05038444]
 [0.20488118 0.30794511 0.36751564]
 [0.99157472 0.81120831 0.69894081]]

 Ceil of the Matrix: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 Floor of the Matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a random 1x4 array and print the random array and its shape.
    
      (use the shape function for finding the shape & use the same random we created here for both the below operations.)

  a) Squeeze the random array and print the squeezed array and its shape.
  b) Expand the random array by one axis and print the expanded array and its shape.

In [8]:
import numpy as np
matrix = np.random.randint(0,10,size=(1,4,2))
print(matrix)
print("The shape of Matrix is: ",np.shape(matrix))
sqz = np.squeeze(matrix)
print("Squeezed: ",sqz)
print("The shape of Matrix is: ",np.shape(sqz)) 
matrix1 = np.expand_dims(matrix,3)
print("Expanded array: \n",matrix1)
print("Shape is ",matrix1.shape)


[[[5 7]
  [7 1]
  [4 4]
  [6 6]]]
The shape of Matrix is:  (1, 4, 2)
Squeezed:  [[5 7]
 [7 1]
 [4 4]
 [6 6]]
The shape of Matrix is:  (4, 2)
Expanded array: 
 [[[[5]
   [7]]

  [[7]
   [1]]

  [[4]
   [4]]

  [[6]
   [6]]]]
Shape is  (1, 4, 2, 1)
