<a href="https://colab.research.google.com/github/anamikaprem/Learn.py/blob/main/TASK_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [1]:
import numpy as np
mat = np.random.randint(0,8,(3,3))
print("\n The Matrix is:\n",mat)
sum = np.sum(mat)
print("\n Sum is :\n",sum)



 The Matrix is:
 [[4 3 2]
 [3 0 4]
 [3 7 2]]

 Sum is :
 28


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [2]:
import numpy as np
mat = np.random.randint(0,8,(3,3))
print("\n The Matrix is:\n",mat)
col = np.sum(mat,axis =0)
print("\n Sum of Columns:\n",col)
row = np.sum(mat,axis =1)
print("\n Sum of Columns:\n",row)



 The Matrix is:
 [[7 6 7]
 [6 4 6]
 [3 3 3]]

 Sum of Columns:
 [16 13 16]

 Sum of Columns:
 [20 16  9]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [3]:
import numpy as np
mat = np.random.randint(0,15,(4,4))
print("\n The Matrix is:\n",mat) 
min = np.min(mat)
print("\n Minimum Value is\n",min) 
max = np.max(mat)
print("\n Maximum Value is\n",max) 
mean = np.mean(mat)
print("\n Minimum Value is\n",mean)


 The Matrix is:
 [[ 0 12 13  5]
 [ 8 14  1  0]
 [ 1  1  0  9]
 [ 8  0  1  0]]

 Minimum Value is
 0

 Maximum Value is
 14

 Minimum Value is
 4.5625


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [4]:
import numpy as np
mat = np.random.randint(0,99,(10,10))
print("\n The Matrix is:\n",mat)
print("\nThe 7th row is :\n",mat[7,:]) 
print("\nThe 4-8th row is :\n",mat[4:8,:])
print("\nThe value at (5,5) is :\n",mat[5,5]) 
print("\nThe 5th column) is :\n",mat[:,5])
print("\nThe 2-5th column) is :\n",mat[:,2:5])



 The Matrix is:
 [[10  2 62 13 92 45 25 48 10  1]
 [98 94 55 89 35 33 63  6 33  5]
 [44 56 27 70 76 63 55 81 72 14]
 [45 28 25 46 13 62 96 70 42 42]
 [98  9 45 54 41 50 73 95 17 49]
 [26 87  1 71 17  6 90 83  0 78]
 [48 24 93 19 87 17 80 96 75 42]
 [86 78 16 54 65  2 68 37 80 39]
 [42 41 55  0 45 29 23 17 84 60]
 [24  3 19 21 30 52 71 11 74 83]]

The 7th row is :
 [86 78 16 54 65  2 68 37 80 39]

The 4-8th row is :
 [[98  9 45 54 41 50 73 95 17 49]
 [26 87  1 71 17  6 90 83  0 78]
 [48 24 93 19 87 17 80 96 75 42]
 [86 78 16 54 65  2 68 37 80 39]]

The value at (5,5) is :
 6

The 5th column) is :
 [45 33 63 62 50  6 17  2 29 52]

The 2-5th column) is :
 [[62 13 92]
 [55 89 35]
 [27 70 76]
 [25 46 13]
 [45 54 41]
 [ 1 71 17]
 [93 19 87]
 [16 54 65]
 [55  0 45]
 [19 21 30]]
