<a href="https://colab.research.google.com/github/anamikaprem/Learn.py/blob/main/TASK_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

N.B: Please find the answers by applying the functions on the matrices

1. Create 2 3×3 matrix with 0-8 and 10-19 as elements in each and perform the vectorize multiplication operations on the matrices.(Outer product, Dot product, Element wise product).

In [3]:
import numpy as np
mat1 = np.random.randint(0,8,(3,3))
mat2 = np.random.randint(10,19,(3,3)) 
print("Matrix A\n" ,mat1) 
print("\nMatrix B\n" ,mat2) 
out = np.multiply.outer(mat1,mat2)
print("Outer Products\n",out) 
dot = np.dot(mat1,mat2)
print("Dot Products\n",dot) 
Ele = np.multiply(mat1,mat2)
print("Element Wise\n",Ele)


Matrix A
 [[2 1 6]
 [0 7 3]
 [2 4 2]]

Matrix B
 [[16 18 17]
 [14 16 14]
 [10 16 13]]
Outer Products
 [[[[ 32  36  34]
   [ 28  32  28]
   [ 20  32  26]]

  [[ 16  18  17]
   [ 14  16  14]
   [ 10  16  13]]

  [[ 96 108 102]
   [ 84  96  84]
   [ 60  96  78]]]


 [[[  0   0   0]
   [  0   0   0]
   [  0   0   0]]

  [[112 126 119]
   [ 98 112  98]
   [ 70 112  91]]

  [[ 48  54  51]
   [ 42  48  42]
   [ 30  48  39]]]


 [[[ 32  36  34]
   [ 28  32  28]
   [ 20  32  26]]

  [[ 64  72  68]
   [ 56  64  56]
   [ 40  64  52]]

  [[ 32  36  34]
   [ 28  32  28]
   [ 20  32  26]]]]
Dot Products
 [[106 148 126]
 [128 160 137]
 [108 132 116]]
Element Wise
 [[ 32  18 102]
 [  0 112  42]
 [ 20  64  26]]


2. Create a 4×4 matrix with 0-16  as elements in it. Add a scalar 4 to the matrix and also multiply it with [1,2,3,4] 1-D matrix by broadcasting. ( Please note to do both the addition and multiplication by broadcasting.)

In [5]:
import numpy as np 
mat = np.random.randint(0,16,(4,4))
print("Matrix is \n", mat) 
#adding 4(scalar)to the matrix
scal = 2
addScal = mat + scal
print("\n Scalar Matrix\n",addScal) 
#matrix broadcasting
nums = np.array([1,2,3,4])
mult = mat * nums
print("\nThe Multiplication by broadcasting\n",mult)


Matrix is 
 [[13  7  9 10]
 [12  1  0  9]
 [ 0  4  0 13]
 [ 0  3 10 14]]

 Scalar Matrix
 [[15  9 11 12]
 [14  3  2 11]
 [ 2  6  2 15]
 [ 2  5 12 16]]

The Multiplication by broadcasting
 [[13 14 27 40]
 [12  2  0 36]
 [ 0  8  0 52]
 [ 0  6 30 56]]
